instrumentation:
    excludes: [
        'lib/entity_generator.js',
        'lib/helpers/question_asker.js'
    ]
check:
    global:
        statements: 90
        lines: 90
        branches: 80
        functions: 90
